### ISSUE TITLE
Investigate Disconnect Issues

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#114]
A client disconnecting causes issues in the game. Sometimes one of the games crashes on disconnect. We need to investigate and identify the cause of this issue so it can be fixed. Also, this is an issue that will be a discussion point for what should happen to a client's party when a disconnect happens.

**Comment by garrettluskey** [comment]
Ideas for disconnected parties.

- Is saved and removed from the map until rejoin.
- Goes to the nearest town and waits for rejoin.
- AI takes control of the party.

**Comment by MaxBosse** [comment]
I don't know how much we want to avoid players abusing game-mechanics, since I assume most people will play this with friends and it is up to them if they want to abuse or not, but the first option could be abused to get out of fights you might lose (logging out and wait for the enemy army to move away before logging back in).

In my opinion the best way to handle a disconnect would be to pause the game to give players the time to reconnect without anything happening to the army.

At the same time however, it should allow (the host?) to select between option 2 and 3. 
Option 2 would be ideal for someone that needs to leave for some time while the others want to continue playing while option 3 would be ideal if someone wants to leave the campaign all together.
Maybe it would be possible to have the party go to the nearest town if the game gets unpaused without the player being back in and option 3 would be achieved by some form of command or option in the menu.
