### ISSUE TITLE
Map Movement Events Missing

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#12]
When navigating to a party, the target party is not synchronized to all clients. Needs to be looked into.

**Comment by araex** [comment]
There's a property `MobileParty.DefaultBehaviorNeedsUpdate` that is currently not being tracked in `Coop.Mod.Patch.CampaignMapMovement`. I also never look into the besieging stuff, that uses some other fields as well.

I think the way to solve this bug is to further look into `MobileParty` and identify:
1. All the methods & property setters that are used to manipulate any map movement state
2. All the internal fields that are actually relevant for the map movement

And then update CampaignMapMovement accordingly.

**Comment by araex** [comment]
Might also be related to https://github.com/Bannerlord-Coop-Team/BannerlordCoop/issues/17

**Comment by garrettluskey** [comment]
I dont think it is directory related to #17. I noticed desync between the host and client with a looter party. Could be an attack event that is not tracked.

**Comment by araex** [comment]
There is an issue when a client party is moving to the host party. This is most likely due to the hosts party being the Campaign.MainParty, so the game supresses movement events.

**Comment by araex** [comment]
To be more precise: MapScreen.HandleLeftMouseButtonClick:

```
PartyBase party = PartyBase.FindParty(visualOfSelectedEntity.PartyIndex);
if (party == PartyBase.MainParty || party == null)
{
    MobileParty.MainParty.SetMoveModeHold();
}
else
{
    // ...
}
```
So it's technically not a missing movement sync, but rather that no movement is generated by the game  at all. This might be a reoccuring issue because MobileParty.MainParty is used all over the place.

**Comment by araex** [comment]
I couldn't really figure out much so far. But just so it doesn't get lost, here are my current findings.

# Movement is sent to all clients
The following is a log output of a host + connected player when moving the hosts party to the connected players party:
![](https://i.imgur.com/QwGpa8w.png)
- Thread 7 is the hosts game instance
- Thread 31 is the hosts server instance
- Thread 10 is the connected players game instance
To explain the log messages in order:
1. Hosts game generates the move request
2. Server ACKs the move request and broadcasts it
3. Hosts game receives the move from the server
4. Connected players game receives the move from the server
5. In the hosts game instance, the his party arrived at the other players party. So a hold is generated. The following events are again the broadcasting of the hold and applying it on all clients including the time stop since no party is moving anymore.

Things to note:
- The move is received by all clients and written to the MobileParty, but apparently it has no effect
- Usually when moving a player party, the game will automatically unpause. In step 4 this does not happen.
- MobileParty.SetMoveModeHold is not called on the connected players end, i investigated this already.

**Comment by garrettluskey** [comment]
> Engaging the main player party with a client party requires an explicit update of both AIs on both game instances - otherwise, it will just not apply.
