### ISSUE TITLE
Provide the best serialization and compression libraries for the whole project

### ISSUE THREAD

**Issue by evorios** [araex/BannerlordCoop#23]
Because we work with network in short time we need effectiveness utilities for serialization/deserialization and compression/decompression. I done some research for it.

**Binary and json serialization/deserialization**

[Good overview](https://aloiskraus.wordpress.com/2019/09/29/net-serialization-benchmark-2019-roundup/)
![Good overview](https://aloiskraus.files.wordpress.com/2019/09/image-11.png)

**Binary**

For simple types we have [NetPacketProcessor](https://revenantx.github.io/LiteNetLib/articles/netserializerusage.html) from [LiteNetLib](https://github.com/RevenantX/LiteNetLib)

For arbitrary objects looks good follow libs:

- [Apex](https://github.com/dbolin/Apex.Serialization)
  fastest, but have some limitations, simple for usage
- [Bois](https://github.com/salarcode/Bois)
  simple for usage, have LZ4 built-in compression
- [MessagePackSharp](https://github.com/neuecc/MessagePack-CSharp)
  separate schema required, big collection of built-in supported types, have LZ4 built-in compression, big community
- [FlatBuffer](https://google.github.io/flatbuffers/flatbuffers_guide_use_c-sharp.html)
  extremely fast serialization, sophisticated usage
- [GroBuf](https://github.com/skbkontur/GroBuf)
  very fast, a large payload is generated as a result, have some useful features

**Json**

[Utf8Json](https://github.com/neuecc/Utf8Json) without a rival

**Compression**

[LZ4](https://github.com/MiloszKrajewski/K4os.Compression.LZ4) without a rival

**Comment by evorios** [comment]
related with #22

**Comment by araex** [comment]
Thanks for the overview. 

I would argue against using a serialization library that uses explicit schemas (such as FlatBuffer) since this is more like to cause additional work with game updates. We should stick to a schemaless approach. 

Additionally, i think it's important we pick a library that generates the serializer code once and is then able to reuse the generated code. We can easily spare the initialization time when booting up the game.

From just a quick glance Apex, Bois and GroBuf all fit those criteria. We could put the serializer code for #22 behind an interface and benchmark the performance for a few of those libraries with actual game objects. @garrettluskey already did some serializer work, maybe he's got some input as well.

**Comment by garrettluskey** [comment]
I have only done work with creating serializable classes. How we package them is still up for debate.

**Comment by evorios** [comment]
Only now, after more intensive work with the transfer of objects between the server and the client, I see that my research is not relevant, because the `RailBitBuffer` and `RailRoom` is the most convenient mechanism for translating objects.

**Comment by garrettluskey** [comment]
I disagree. Although railgun may provide some serialization libraries, it may not be optimal for large object transfer. Railgun, from my understanding, is used to synchronize the server and clients. The object we would have to initially transfer such as a character created when joining needs to be transferred separately.

**Comment by garrettluskey** [comment]
Adding on-hold as this is a lower priority than synchronization.
