### ISSUE TITLE
SettlementComponent Sync

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#246]
Town interactions need to be synchronized via RPC and value persistence. Look into what other sync might be needed and implement.

The following fields will need to be synchronized

- [ ] _tradeBound
- [ ] Gold
- [ ] _owner

The following methods will be disabled on all clients
- [ ] ChangeGold

See https://github.com/Bannerlord-Coop-Team/BannerlordCoop/blob/development/source/Coop/Mod/Persistence/Party/EventPartyMoveTo.cs. We use Railgun for RPC, https://github.com/araex/RailgunNet/blob/master/RailgunNet/Logic/RailEvent.cs

**Comment by uvaysbazaev** [comment]
One year passed since I saw this mod, is there any progress?

**Comment by thomasDelaporte** [comment]
So we reviewed the fields to synchronize:
- Owner
- Gold
- IsTaken

We have problems with the fields (IsTaken), since Harmony / our system does not manage fields, only properties.
There is a branch already made ([sync-settlement-component](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/tree/feature/sync-settlement-component)) with the basic commands but the synchronization of the "Gold" does not work for the moment.

**Comment by garrettluskey** [comment]
Issue updated to #736

**Comment by garrettluskey** [comment]
Issue updated to #736
