### ISSUE TITLE
Is the handler executed twice?

### ISSUE THREAD

**Issue by evorios** [araex/BannerlordCoop#29]
Event subscriptions:
```
FieldAccessGroup<MobileParty, MovementData> TargetPosition = AddField<Vec2>("_targetPosition"): game event
m_Environment.TargetPosition.SetHandler(m_Instance, GoToPosition) : main handler
reg.AddEventType<EventPartyMoveTo>(): server/client event
State.OnMovementChanged += UpdateLocalMovement
```
Sequence of execute:
```
TargetPosition = <UI click> : handler executed
GoToPosition()
	Room.RaiseEvent<EventPartyMoveTo>() : event fired
EventPartyMoveTo.Execute()
	entity.State.Movement = Movement
	if (!m_Movement.Equals(value)) : stop here if handler executed twice
		OnMovementChanged?.Invoke() : event fired
UpdateLocalMovement()
	m_Environment.TargetPosition.SetTyped(party, data) : handler executed?
GoToPosition()
...
```
@araex Is the handler executed twice?

**Comment by araex** [comment]
Handlers should not be called twice. Your sequence seems to mix up client and server. We can divide a change up into 3 stages:

1. The game wants to change the move to position of a party. Instead of applying that change, we intercept it and send it to the server.
2. The server receives all change requests and executes them if the sender of the change request is authorized to make changes. If applied, the server informs all clients about the change.
3. The clients receive a change from the server and apply it to their local game state.

That's the high level view of the system. Here's a more detailed look at the your example:
1. The client detects changes to the fields described in the patch `CampaignMapMovement`. Specifically, it prefixes all calls to  `MobilePartyPatch.Setters`.
2. The injected prefix to the method writes all changes to a buffer and does not call the original setter.
3. Once per frame, all buffered changes are processed and the registered changed handlers are called. That's `GoToPosition` in your example.
4. A `RailEvent<EventPartyMoveTo>` is raised.
5. The `RailEvent` is sent to the server and will be processed there. See `EventPartyMoveTo.Execute` which is called server side. This changes the serverside `MobilePartyState`.
6. The change to the `MobilePartyState` is noticed by Railgun and broadcast to all clients. Including the originator of the event. This is a synchronized authoritative state change, not an event!
7. The client receives the change and applies it to its local instance of `MobilePartyState`. This invokes on changed handler, in your case `UpdateLocalMovement`.
8. UpdateLocalMovement calls back into the `CampaignMapMovement` and invokes the original setter. The new position is now applied.

Here's a sequence diagram for setting the move to position: https://i.imgur.com/ejrypIx.png .

**Comment by evorios** [comment]
Thank you. It has become much clearer.
