### ISSUE TITLE
Steam interface

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#41]
We need a way of getting steam names and a GUID for each player.

Create a file called SteamAPI and have functions for getting Steam name and account number.

Steamworks.NET has SteamUser which probably has all the functionality needed

**Acceptance Criteria**
- Both functions implemented
- Functions are proven working with tests

**Comment by araex** [comment]
I did try some things in the very beginning, see https://github.com/Bannerlord-Coop-Team/BannerlordCoop/blob/development/source/Coop/NetImpl/Steam/NetworkSteam.cs . That uses Bannerlords existing Steam app id to initialize the SteamAPI which allows you to use it just like it's your own game. That didn't seem to cause any issues.

The idea was to provide an `INetwork` and implement it for the different platforms like steam and the epic launcher. The implementation should also be able to initiate a connection to another player through the platforms friends feature (right click -> join game). Using steam / epic for that is the prefered way, as those are already set up on the users PC and do not require any port forwarding or router configuration.

**Comment by garrettluskey** [comment]
It looks that this only gets the app id of the game. This issue is preparation to assign names to peers. Currently, all connections are named unknown.

**Comment by araex** [comment]
Yes, but the SteamAPI initialization is already handled there.

**Comment by tristanka** [comment]
Currently I have a branch with a SteamAPI class that successfully gets the user's SteamID and "PersonaName" (your Steam name that you can change, not your account name). Few questions:

• SteamAPI is also a class in Steamworks, so do we want a different name for convenience's sake? 

• Should the SteamAPI be separate from the NetworkSteam implementation? I assume we don't want to bloat NetworkSteam with a bunch of methods for API calls since it seems more of a connection manager

• Currently the SteamAPI class has a private NetworkSteam field that I'm instantiating and calling Connect() on in the constructor to make sure the connection exists any time we create a SteamAPI object to be used.  Seems heavy-handed but I'm not sure what the best practice would be. Ideas?

**Comment by garrettluskey** [comment]
> SteamAPI is also a class in Steamworks, so do we want a different name for convenience's sake?

Whichever is the official Steam library would be best to use.

> Should the SteamAPI be separate from the NetworkSteam implementation? I assume we don't want to bloat NetworkSteam with a bunch of methods for API calls since it seems more of a connection manager

If we can separate it that would be great. I'm not very familiar with the Steam implementation

> Currently the SteamAPI class has a private NetworkSteam field that I'm instantiating and calling Connect() on in the constructor to make sure the connection exists any time we create a SteamAPI object to be used. Seems heavy-handed but I'm not sure what the best practice would be. Ideas?

I would be able to better answer this when you submit a pull request
