### ISSUE TITLE
Implement Missions DI

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#454]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Currently we live in a bad code base that does not use dependency injection. We need to fix this and the library that we should use is AutoFac (if you think a better library exists, please recommend it).

## Intended Design

N/A

## Location

Create a new branch based from `taverns-MessageBrokerRefactor`

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] Classes now use AutoFac for dependency injection
- [ ] Any dependency without an interface now has an interface

**Comment by smudge202** [comment]
Per discord conversation, we'll use [`Microsoft.Extensions.DependencyInjection.Abstractions`](https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection) throughout dependency modules, composition roots can use [`Autofac.Extensions.DependencyInjection`](https://github.com/autofac/Autofac.Extensions.DependencyInjection) so that we have a shared Autofac DI base.
