### ISSUE TITLE
Setup CI for project

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#67]
We want to verify that the project builds and all tests pass before a merge request is accepted

**Comment by garrettluskey** [comment]
@araex want to look into this?

**Comment by Moggers** [comment]
Any idea what tool you want to use for this? (I've heard AppVeyor is used for a lot of CI/CD targeting Windows.. Though I'm not sure why aside from maybe just better than usual support for Windows native stuff.)

**Comment by garrettluskey** [comment]
Github actions would be best for now. Eventually, we will have to setup a local custom runner due to Bannerlord licensing. For now, we can set up actions for dotnet compiling and running xunit tests.

**Comment by araex** [comment]
I was made aware that the guys over at BUTR are generating [reference assemblies](https://docs.microsoft.com/en-us/dotnet/standard/assembly/reference-assemblies) automatically for bannerlord and are making them available through a nuget feed. 

An example of a user of that feed can be found [here](https://github.com/BUTR/Bannerlord.UIExtenderEx/blob/dev/src/nuget.config). Credentials are apparently necessary because github does not allow anonymous access, we can create use some dummy user for that. The credentials need to be xml encoded.

Thanks to Aragas from the BUTR team the suggestions.

**Comment by ghost** [comment]
I agree with this idea, I think in order to get around the building aspect of the project (especially on custom runners), we should supply the reference assemblies of our module through a Nuget Feed which can be taken in, then we pull in and build that with the existing API provided, this may be the way we get around it, however a Custom Runner is going to need a legal set of M&B2 files, is there any documentation regarding that?
