### ISSUE TITLE
Encyclopedia Pauses Game

### ISSUE THREAD

**Issue by EgardA** [araex/BannerlordCoop#675]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Currently, the game gets paused when you open the Encyclopedia. Encyclopedia can be opened pressing 'N'.

## Intended Design

Game should not pause when opened

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

**Comment by orfolei** [comment]
This is not just an encyclopedia issue, it also happens in other menus. The problem is that `GameStateManager` is only calling the `Tick` method on the active state, which is the menu state instead of `MapState` when a menu is open.

I suggest injecting some additional code into `TaleWorlds.Core.GameStateManager.OnTick(float)` to ensure the Tick method is always called on `MapState` when it is available.

(the following code has not been tested)
```cs
// Check if the current ActiveState is not a MapState
if (!(gameStateManager.ActiveState is MapState))
{
    // Get the MapState instance, if available
    MapState mapState = gameStateManager.LastOrDefault<MapState>();

    // Call OnTick on the MapState, if it exists
    mapState?.OnTick(dt); // dt comes from the method parameters
}
```

**Comment by EgardA** [comment]
Sounds like a very good fix for this and related issues, are you familiar with creating a transpiler with harmony if you want to try to implement this?
