### ISSUE TITLE
Time not updating with player movement from separate party

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#75]
Time controls are working as intended. Currently when parties move the time does not update on all clients. Event for move must not be hooked properly.

**Comment by garrettluskey** [comment]
Events sent to server using RailGun don't appear to get raised past RailServer process commands for packet with events. May also relate to #73

**Comment by araex** [comment]
Not a movement issue, the hooks work fine.

The issue boils down to the way time flow is controlled by the game. The main party is special in that it can stop & start time based on internal state. Since we introduced a second main party (or more accurately different main parties on every client), that special handling needs to be patched as well. Specifically the Campaign.IsMainPartyWaiting needs to return true only if all player controlled parties are currently waiting, not just the main party.
